### ISSUE TITLE
Your program contains a virus?

### ISSUE THREAD

**Issue by Virginityrocks** [khanhas/Notch#5]
This significantly slowed down my PC after pressing the Light/Dark app mode button. Even deleting it and restarting the PC does not fix it. All Rainmeter skins have now slowed to a crawl and my PC is really fucking slow. What did you write?!

I may need to reinstall Windows!

EDIT: Found solution. "Power saver" was pressed in battery app that SIGNIFICANTLY HOLY SHIT slowed down my computer to the point where I was barely even able to open the start menu. Rainmeter become virtually unusable. And once the button was pressed, I was totally unable to even use Notch to disable the option. I would highly suggest you remove this option entirely from your skin.

**Comment by thomaskoppelaar** [comment]
PEBCAK

**Comment by Virginityrocks** [comment]
You're creating a program that "pebcak"s use. Engineers also fail.

**Comment by Virginityrocks** [comment]
There shouldn't be a button in your program that will disable someone's PC
without any kind of confirmation box.
